### ISSUE TITLE
Make dotnet tool check if it is out of date when invoked

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules-updater#2]
To help users have the latest version of the updater tool installed, the tool should query nuget.org/look at github releases and see if it has the latest version installed.

This could probably be done by checking the the version timestamp in the asesmbly and compare it to the latest released to nuget.org.

If there is a newer version, the tools should output the approprate `dotnet` command to update the tool.

**Comment by davidkallesen** [comment]
Api for version lookup: https://api.nuget.org/v3-flatcontainer/atc-coding-rules-updater/index.json

**Comment by davidkallesen** [comment]
Fixed in PR: https://github.com/atc-net/atc-coding-rules-updater/commit/b1e4db22abf02168dbc0cb4f6a2253864d6231d2
