### ISSUE TITLE
EnableNETAnalyzers set in csproj causes build errors after add of ATC rules

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#43]
If the project has:

```xml
 <EnableNETAnalyzers>true</EnableNETAnalyzers>
```

set already, then running the atc-rules-updater to add rules etc. will cause the project to fail with something like:

```
CSC : error CS8034: Unable to load Analyzer assembly C:\Users\extjkrag\.nuget\packages\microsoft.codeanalysis.netanalyzers\5.0.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Assembly with same name is already loaded [C:\Users\extjkrag\source\repos\XYZ\XYX.Test\XYX.Test.csproj]
CSC : error CS8034: Unable to load Analyzer assembly C:\Users\extjkrag\.nuget\packages\microsoft.codeanalysis.netanalyzers\5.0.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.NetAnalyzers.dll : Assembly with same name is already loaded [C:\Users\extjkrag\source\repos\XYX\XYX.Test\XYX.Test.csproj]
```

Removing the EnableNETAnalyzers declaration so that it is only included in Directory.build.props fixes this issue, but this is not very obvious to end users, and maybe the updater cli should handle this in some nice way?

**Comment by davidkallesen** [comment]
Fixed in PR: https://github.com/atc-net/atc-coding-rules-updater/commit/b1e4db22abf02168dbc0cb4f6a2253864d6231d2
