### ISSUE TITLE
.editorconfig files should probably have a separate "Custom" section for non-coding-style rules

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#45]
If the user wants to override the default editor rules (e.g. whitespace) this can currently only really be done in the Custom section for coding rules, but since this involves specifying new file-extension wildcards, it may cause al following rules to be ignored for cs files. 

This is closely related to issue #44

**Comment by davidkallesen** [comment]
Fixed in PR: https://github.com/atc-net/atc-coding-rules-updater/commit/b1e4db22abf02168dbc0cb4f6a2253864d6231d2
