### ISSUE TITLE
Split AtcAnalyzerProviderBaseRules.json cache into multiple files

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#46]
Instead of failing hard and not writing anything on errors, the caching mechanism should instead rely on one file per provider, and thus be able to cache collected rules for all non-failing rule-sets.

**Comment by JKrag** [comment]
This has been done in conjunction with the work on branch https://github.com/atc-net/atc-coding-rules-updater/tree/feature/multi-distributions which will most likely end up as something like a 2.0 release.

**Comment by davidkallesen** [comment]
Fixed in PR #b1e4db22abf02168dbc0cb4f6a2253864d6231d2
