### ISSUE TITLE
Updater still slightly confused about available versions

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#66]
I was running version 2.0.82. 
First off, very happy to see that it now correctly reposts the right version with `--version` and also notifies me about an available update.

But it seems that it is still slightly confused about what is available.

```
$ atcu --sanity-check .
  ____            _                                      _           _
 |  _ \   _   _  | |   ___   ___     _   _   _ __     __| |   __ _  | |_    ___   _ __ 
 | |_) | | | | | | |  / _ \ / __|   | | | | | '_ \   / _` |  / _` | | __|  / _ \ | '__|
 |  _ <  | |_| | | | |  __/ \__ \   | |_| | | |_) | | (_| | | (_| | | |_  |  __/ | |   
 |_| \_\  \__,_| |_|  \___| |___/    \__,_| | .__/   \__,_|  \__,_|  \__|  \___| |_|   
                                            |_|
Version 2.0.88 of ATC-Coding-Rules-Updater is available!
You are running version 2.0.82.41834
```

finds new version 2.0.88 but then immediately updates to 2.0.92 ;-)

```
$ dotnet tool update --global atc-coding-rules-updater
Tool 'atc-coding-rules-updater' was successfully updated from version '2.0.82' to version '2.0.92'.
```

**Comment by davidkallesen** [comment]
Fix in [atc](https://github.com/atc-net/atc) - https://github.com/atc-net/atc/commit/59265447d5cc181c2ccd9520568e02ac858734f1

Fix in [atc-coding-rules-updater](https://github.com/atc-net/atc-coding-rules-updater) - https://github.com/atc-net/atc-coding-rules-updater/commit/28c7bab51071ffa3c7a231809325d4c6a5114776
