### ISSUE TITLE
Should updater fail if no internet connection?

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#68]
I ran the updater today, and the output made me indirectly realize that my internet connection was completely down. The updaters error message about "no such host is known" are correct, but don't really tell the user what it was trying to fetch.
Also, in the end, it just continues "silently" to the .editorconfig / temp. suppressions part, and ends up reporting a perfectly clean green "Done" without any messages about the possible side effects of the previous sections not running correctly.
In my case, it was all on one screen, and I noticed the warnings, but if there had been more suppression output, I might have missed the initial red lines.

![atc-rules-updater-when-network-down](https://user-images.githubusercontent.com/1712950/152782748-cfa289db-f388-4a72-9d41-098e7a65699a.png)

I am not sure what would be the best behavior here, but figured I would post the screenshot while I had it, for further discussion.

**Comment by davidkallesen** [comment]
Fix in release 2.0.119:  https://github.com/atc-net/atc-coding-rules-updater/runs/5232626928?check_suite_focus=true
