### ISSUE TITLE
Improve output for non-standard folder names

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules-updater#69]
I had a new project that needed coding-rules added. This project did not have the default `src/` and `test/` folders, but rather `ProjectName` and `ProjectNameTest` subfolders, so I started by running `atc-coding-rules-updater options-file create .` to create a default `atc-coding-rules-updater.json` file, and then edited the paths in this one.

Afterwards, I ran the `run` subcommand to add all the coding-rules stuff, and this ran perfectly smooth. However, the actual output says:

![atc-coding-rules-src-test-folder-names](https://user-images.githubusercontent.com/1712950/152789947-e96e5d18-f6a8-43e6-a1cb-4d10ace3b8fb.png)

Since the paths in the output are formatted to look like actual paths `src/.editorconfig` then maybe it would be less confusing if they actually printed the correct path to the file that was created e.g. `ProjectNameTest/.editorconfig` rather than the "conceptual" `test/` path?

Maybe there is a good reason why it does what it currently does?

**Comment by davidkallesen** [comment]
Fix in version 2.0.117
